spring.application.name=workerInformation

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/worker_information
spring.datasource.username=root
spring.datasource.password=Aswin@21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
